### ISSUE TITLE
1.8 Not Supported

### ISSUE THREAD

**Issue by dixonwille** [jmoiron/sqlx#312]
Currently working on a project that uses vendoring. I updated all the references to the latest on master (even tried tagged versions) but it seems that I cannot build with this package in Go 1.8.1. When downgrading to 1.7.4_2 it works great. If I may advise to use [sql/driver](https://golang.org/pkg/database/sql/driver/) package as that was included in 1.8. There were some changes that they said were minor but maybe not but recommend driver packages to look at the above link [Go1.8 Minor Changes](https://golang.org/doc/go1.8#minor_library_changes). 

```
vendor/github.com/jmoiron/sqlx/sqlx_context.go:20: db.PingContext undefined (type *DB has no field or method PingContext)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:122: cannot use db (type *DB) as type namedPreparerContext in argument to prepareNamedContext:
	*DB does not implement namedPreparerContext (missing PrepareContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:128: cannot use db (type *DB) as type ExtContext in argument to NamedQueryContext:
	*DB does not implement ExtContext (missing ExecContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:134: cannot use db (type *DB) as type ExtContext in argument to NamedExecContext:
	*DB does not implement ExtContext (missing ExecContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:140: cannot use db (type *DB) as type QueryerContext in argument to SelectContext:
	*DB does not implement QueryerContext (missing QueryContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:147: cannot use db (type *DB) as type QueryerContext in argument to GetContext:
	*DB does not implement QueryerContext (missing QueryContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:155: cannot use db (type *DB) as type PreparerContext in argument to PreparexContext:
	*DB does not implement PreparerContext (missing PrepareContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:161: db.DB.QueryContext undefined (type *sql.DB has no field or method QueryContext)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:182: undefined: sql.TxOptions
vendor/github.com/jmoiron/sqlx/sqlx_context.go:203: undefined: sql.TxOptions
vendor/github.com/jmoiron/sqlx/sqlx_context.go:161: too many errors
```

**Comment by dixonwille** [comment]
#278 Seems to be the commit that may have broke it for 1.8... I love the idea to use the new context package but if it breaks 1.8...

**Comment by jmoiron** [comment]
Have you just upgraded from 1.7.x?  I'm wondering if there were some things cached that do not support the new context API.   Works for me locally:

```sh
$GOPATH/src/github.com/jmoiron/sqlx (master)$ go version
go version go1.8.1 linux/amd64
$GOPATH/src/github.com/jmoiron/sqlx (master)$ go build
```

**Comment by jmoiron** [comment]
The changesets you are referring to _add_ support for the new 1.8.x `context.Context` methods that were added to `database/sql`.  They are behind a build-tag so that they should not build with earlier versions of Go.  Perhaps there is something going on with the vendoring?  Do you have a different version of sqlx somewhere else in your GOPATH?

**Comment by dixonwille** [comment]
Thanks for the quick response!!

Just removed the older version in GOPATH and ran with `go build -a` to force a rebuild of all packages both of which still reproduce the same outcome...

```
willdixon@willd-mbp:~/Go/src/ac.st/realm/swarm
🐧  go version
go version go1.8.1 darwin/amd64
willdixon@willd-mbp:~/Go/src/ac.st/realm/swarm
🐧  go build -a .
# ac.st/realm/swarm/vendor/github.com/jmoiron/sqlx
vendor/github.com/jmoiron/sqlx/named_context.go:41: n.Stmt.ExecContext undefined (type *Stmt has no field or method ExecContext)
vendor/github.com/jmoiron/sqlx/named_context.go:41: not enough arguments to return
vendor/github.com/jmoiron/sqlx/named_context.go:51: n.Stmt.QueryContext undefined (type *Stmt has no field or method QueryContext)
vendor/github.com/jmoiron/sqlx/named_context.go:51: not enough arguments to return
vendor/github.com/jmoiron/sqlx/sqlx_context.go:20: db.PingContext undefined (type *DB has no field or method PingContext)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:122: cannot use db (type *DB) as type namedPreparerContext in argument to prepareNamedContext:
	*DB does not implement namedPreparerContext (missing PrepareContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:128: cannot use db (type *DB) as type ExtContext in argument to NamedQueryContext:
	*DB does not implement ExtContext (missing ExecContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:134: cannot use db (type *DB) as type ExtContext in argument to NamedExecContext:
	*DB does not implement ExtContext (missing ExecContext method)
vendor/github.com/jmoiron/sqlx/sqlx_context.go:182: undefined: sql.TxOptions
vendor/github.com/jmoiron/sqlx/sqlx_context.go:203: undefined: sql.TxOptions
vendor/github.com/jmoiron/sqlx/sqlx_context.go:134: too many errors
```

I use homebrew and have been on 1.8 since it came out. Just inherited this project from co-worker (who was using 1.7 at the time). Using homebrew to switch between versions easily. 

Here is the commit hash d9bd385d68c068f1fabb5057e3dedcbcbb039d0f that is in the vendor.json which is the latest as of today...

**Comment by dixonwille** [comment]
Also, I did notice those two files are only compiled for 1.8 via `// +build go1.8` that is why 1.7 works for me? this is truly puzzling

**Comment by jmoiron** [comment]
Yes and they contain functions that reference the new interface for database/sql in 1.8.x

Is it possible you're vendoring or otherwise changing the basic sql package?

**Comment by dixonwille** [comment]
Have not touched `GOROOT` and it is not in the vendor path either. According to the first and third error the `Stmt` struct doesn't have those methods but `qStmt` does. Wondering if the following errors are similar (as the second and fourth are related to the first and thrid)? I'll pull down on my windows and linux and see if it is platform issue.

**Comment by dixonwille** [comment]
Lemme make sure I am following logic

1. Error Thrown https://github.com/jmoiron/sqlx/blob/master/named_context.go#L41
2. Because the object created https://github.com/jmoiron/sqlx/blob/master/named_context.go#L23 does not have the Method `ExecContext`
3. `PreparexContext` returns `Stmt` struct https://github.com/jmoiron/sqlx/blob/master/sqlx_context.go#L68
4. Which does not have the `ExecContext` method in  https://github.com/jmoiron/sqlx/blob/master/sqlx_context.go#L284-#L314 or https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L499-#L535

So I don't see how it is compiling on yours?

**Comment by dixonwille** [comment]
Don't know much about how SQL drivers work though that is why I didn't make a PR though. I can attempt one if you think this is an issue?

**Comment by jmoiron** [comment]
They eventually embed `sql.Stmt`, which [does implement ExecContext](https://golang.org/pkg/database/sql/#Stmt.ExecContext).  I suspect this is an issue in your build environment but I haven't experienced this so I don't know exactly what it would be.  It seems that you are building with a 1.8.1 compiler a `database/sql` library that does _not_ have `ExecContext`;  is there any possibility that you have a `vendor/database/sql` directory?

**Comment by dixonwille** [comment]
Well, it may be my mac... Got home and booted Arch and builds fine. Lemme see if I can hunt down the issue. Also, `database/sql` is not vendored I checked.

Thanks for helping!

**Comment by dixonwille** [comment]
it's not vendoring as I can pull this package then try and build with same issues. I am checking GOROOT now but nothing stands out

**Comment by dixonwille** [comment]
@jmoiron thanks for the help. It was my `GOROOT`. I had a 1.7 `GOROOT` because I built from source a while back and forgot about it. So I was still referencing the old `GOROOT` and not the package managers version!

Again thanks for the time spent helping me!

**Comment by jmoiron** [comment]
Ah great!  Glad you figured it out!  `GOROOT` would definitely impact your version of the stdlib.  I suppose that is one disadvantage of having build tags dependent on the compiler version.  I'll keep this in mind if anyone runs into these types of problems in the future!

FWIW, I use https://github.com/travis-ci/gimme to manage different Go versions both at work and for personal use.  I had a little shell script at some point, but `gimme` is continuously updated and works well across platforms :)

**Comment by dixonwille** [comment]
I will look into running locally. I did notice travis-ci uses it so its gotta work right haha.
